name: Create Release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: 'yarn'

      - run: yarn --frozen-lockfile

      - name: Configure git identity
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Release
        id: release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEFTHOOK: 0
